repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.0
  hooks:
    # Run the formatter.
    - id: ruff-format
    # Run the linter.
    - id: ruff
      args: [ --fix ]
